# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.19

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/raghusaripalli/Downloads/cmake-3.19.4-Linux-x86_64/bin/cmake

# The command to remove a file.
RM = /home/raghusaripalli/Downloads/cmake-3.19.4-Linux-x86_64/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/raghusaripalli/Desktop/DBI

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/raghusaripalli/Desktop/DBI

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/raghusaripalli/Downloads/cmake-3.19.4-Linux-x86_64/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/home/raghusaripalli/Downloads/cmake-3.19.4-Linux-x86_64/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/raghusaripalli/Desktop/DBI/CMakeFiles /home/raghusaripalli/Desktop/DBI//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/raghusaripalli/Desktop/DBI/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

#=============================================================================
# Target rules for targets named gTests

# Build rule for target.
gTests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gTests
.PHONY : gTests

# fast build rule for target.
gTests/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gTests.dir/build.make CMakeFiles/gTests.dir/build
.PHONY : gTests/fast

#=============================================================================
# Target rules for targets named test.out

# Build rule for target.
test.out: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test.out
.PHONY : test.out

# fast build rule for target.
test.out/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.out.dir/build.make CMakeFiles/test.out.dir/build
.PHONY : test.out/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) $(MAKESILENT) -f gtest/CMakeFiles/gtest_main.dir/build.make gtest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) $(MAKESILENT) -f gtest/CMakeFiles/gtest.dir/build.make gtest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

BigQ.o: BigQ.cc.o

.PHONY : BigQ.o

# target to build an object file
BigQ.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/BigQ.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gTests.dir/build.make CMakeFiles/gTests.dir/BigQ.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.out.dir/build.make CMakeFiles/test.out.dir/BigQ.cc.o
.PHONY : BigQ.cc.o

BigQ.i: BigQ.cc.i

.PHONY : BigQ.i

# target to preprocess a source file
BigQ.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/BigQ.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gTests.dir/build.make CMakeFiles/gTests.dir/BigQ.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.out.dir/build.make CMakeFiles/test.out.dir/BigQ.cc.i
.PHONY : BigQ.cc.i

BigQ.s: BigQ.cc.s

.PHONY : BigQ.s

# target to generate assembly for a file
BigQ.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/BigQ.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gTests.dir/build.make CMakeFiles/gTests.dir/BigQ.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.out.dir/build.make CMakeFiles/test.out.dir/BigQ.cc.s
.PHONY : BigQ.cc.s

Comparison.o: Comparison.cc.o

.PHONY : Comparison.o

# target to build an object file
Comparison.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Comparison.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gTests.dir/build.make CMakeFiles/gTests.dir/Comparison.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.out.dir/build.make CMakeFiles/test.out.dir/Comparison.cc.o
.PHONY : Comparison.cc.o

Comparison.i: Comparison.cc.i

.PHONY : Comparison.i

# target to preprocess a source file
Comparison.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Comparison.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gTests.dir/build.make CMakeFiles/gTests.dir/Comparison.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.out.dir/build.make CMakeFiles/test.out.dir/Comparison.cc.i
.PHONY : Comparison.cc.i

Comparison.s: Comparison.cc.s

.PHONY : Comparison.s

# target to generate assembly for a file
Comparison.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Comparison.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gTests.dir/build.make CMakeFiles/gTests.dir/Comparison.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.out.dir/build.make CMakeFiles/test.out.dir/Comparison.cc.s
.PHONY : Comparison.cc.s

ComparisonEngine.o: ComparisonEngine.cc.o

.PHONY : ComparisonEngine.o

# target to build an object file
ComparisonEngine.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/ComparisonEngine.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gTests.dir/build.make CMakeFiles/gTests.dir/ComparisonEngine.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.out.dir/build.make CMakeFiles/test.out.dir/ComparisonEngine.cc.o
.PHONY : ComparisonEngine.cc.o

ComparisonEngine.i: ComparisonEngine.cc.i

.PHONY : ComparisonEngine.i

# target to preprocess a source file
ComparisonEngine.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/ComparisonEngine.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gTests.dir/build.make CMakeFiles/gTests.dir/ComparisonEngine.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.out.dir/build.make CMakeFiles/test.out.dir/ComparisonEngine.cc.i
.PHONY : ComparisonEngine.cc.i

ComparisonEngine.s: ComparisonEngine.cc.s

.PHONY : ComparisonEngine.s

# target to generate assembly for a file
ComparisonEngine.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/ComparisonEngine.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gTests.dir/build.make CMakeFiles/gTests.dir/ComparisonEngine.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.out.dir/build.make CMakeFiles/test.out.dir/ComparisonEngine.cc.s
.PHONY : ComparisonEngine.cc.s

DBFile.o: DBFile.cc.o

.PHONY : DBFile.o

# target to build an object file
DBFile.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/DBFile.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gTests.dir/build.make CMakeFiles/gTests.dir/DBFile.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.out.dir/build.make CMakeFiles/test.out.dir/DBFile.cc.o
.PHONY : DBFile.cc.o

DBFile.i: DBFile.cc.i

.PHONY : DBFile.i

# target to preprocess a source file
DBFile.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/DBFile.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gTests.dir/build.make CMakeFiles/gTests.dir/DBFile.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.out.dir/build.make CMakeFiles/test.out.dir/DBFile.cc.i
.PHONY : DBFile.cc.i

DBFile.s: DBFile.cc.s

.PHONY : DBFile.s

# target to generate assembly for a file
DBFile.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/DBFile.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gTests.dir/build.make CMakeFiles/gTests.dir/DBFile.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.out.dir/build.make CMakeFiles/test.out.dir/DBFile.cc.s
.PHONY : DBFile.cc.s

File.o: File.cc.o

.PHONY : File.o

# target to build an object file
File.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/File.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gTests.dir/build.make CMakeFiles/gTests.dir/File.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.out.dir/build.make CMakeFiles/test.out.dir/File.cc.o
.PHONY : File.cc.o

File.i: File.cc.i

.PHONY : File.i

# target to preprocess a source file
File.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/File.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gTests.dir/build.make CMakeFiles/gTests.dir/File.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.out.dir/build.make CMakeFiles/test.out.dir/File.cc.i
.PHONY : File.cc.i

File.s: File.cc.s

.PHONY : File.s

# target to generate assembly for a file
File.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/File.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gTests.dir/build.make CMakeFiles/gTests.dir/File.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.out.dir/build.make CMakeFiles/test.out.dir/File.cc.s
.PHONY : File.cc.s

Heap.o: Heap.cc.o

.PHONY : Heap.o

# target to build an object file
Heap.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Heap.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gTests.dir/build.make CMakeFiles/gTests.dir/Heap.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.out.dir/build.make CMakeFiles/test.out.dir/Heap.cc.o
.PHONY : Heap.cc.o

Heap.i: Heap.cc.i

.PHONY : Heap.i

# target to preprocess a source file
Heap.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Heap.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gTests.dir/build.make CMakeFiles/gTests.dir/Heap.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.out.dir/build.make CMakeFiles/test.out.dir/Heap.cc.i
.PHONY : Heap.cc.i

Heap.s: Heap.cc.s

.PHONY : Heap.s

# target to generate assembly for a file
Heap.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Heap.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gTests.dir/build.make CMakeFiles/gTests.dir/Heap.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.out.dir/build.make CMakeFiles/test.out.dir/Heap.cc.s
.PHONY : Heap.cc.s

Pipe.o: Pipe.cc.o

.PHONY : Pipe.o

# target to build an object file
Pipe.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Pipe.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gTests.dir/build.make CMakeFiles/gTests.dir/Pipe.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.out.dir/build.make CMakeFiles/test.out.dir/Pipe.cc.o
.PHONY : Pipe.cc.o

Pipe.i: Pipe.cc.i

.PHONY : Pipe.i

# target to preprocess a source file
Pipe.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Pipe.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gTests.dir/build.make CMakeFiles/gTests.dir/Pipe.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.out.dir/build.make CMakeFiles/test.out.dir/Pipe.cc.i
.PHONY : Pipe.cc.i

Pipe.s: Pipe.cc.s

.PHONY : Pipe.s

# target to generate assembly for a file
Pipe.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Pipe.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gTests.dir/build.make CMakeFiles/gTests.dir/Pipe.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.out.dir/build.make CMakeFiles/test.out.dir/Pipe.cc.s
.PHONY : Pipe.cc.s

Record.o: Record.cc.o

.PHONY : Record.o

# target to build an object file
Record.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Record.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gTests.dir/build.make CMakeFiles/gTests.dir/Record.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.out.dir/build.make CMakeFiles/test.out.dir/Record.cc.o
.PHONY : Record.cc.o

Record.i: Record.cc.i

.PHONY : Record.i

# target to preprocess a source file
Record.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Record.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gTests.dir/build.make CMakeFiles/gTests.dir/Record.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.out.dir/build.make CMakeFiles/test.out.dir/Record.cc.i
.PHONY : Record.cc.i

Record.s: Record.cc.s

.PHONY : Record.s

# target to generate assembly for a file
Record.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Record.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gTests.dir/build.make CMakeFiles/gTests.dir/Record.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.out.dir/build.make CMakeFiles/test.out.dir/Record.cc.s
.PHONY : Record.cc.s

Schema.o: Schema.cc.o

.PHONY : Schema.o

# target to build an object file
Schema.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Schema.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gTests.dir/build.make CMakeFiles/gTests.dir/Schema.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.out.dir/build.make CMakeFiles/test.out.dir/Schema.cc.o
.PHONY : Schema.cc.o

Schema.i: Schema.cc.i

.PHONY : Schema.i

# target to preprocess a source file
Schema.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Schema.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gTests.dir/build.make CMakeFiles/gTests.dir/Schema.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.out.dir/build.make CMakeFiles/test.out.dir/Schema.cc.i
.PHONY : Schema.cc.i

Schema.s: Schema.cc.s

.PHONY : Schema.s

# target to generate assembly for a file
Schema.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Schema.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gTests.dir/build.make CMakeFiles/gTests.dir/Schema.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.out.dir/build.make CMakeFiles/test.out.dir/Schema.cc.s
.PHONY : Schema.cc.s

TwoWayList.o: TwoWayList.cc.o

.PHONY : TwoWayList.o

# target to build an object file
TwoWayList.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/TwoWayList.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gTests.dir/build.make CMakeFiles/gTests.dir/TwoWayList.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.out.dir/build.make CMakeFiles/test.out.dir/TwoWayList.cc.o
.PHONY : TwoWayList.cc.o

TwoWayList.i: TwoWayList.cc.i

.PHONY : TwoWayList.i

# target to preprocess a source file
TwoWayList.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/TwoWayList.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gTests.dir/build.make CMakeFiles/gTests.dir/TwoWayList.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.out.dir/build.make CMakeFiles/test.out.dir/TwoWayList.cc.i
.PHONY : TwoWayList.cc.i

TwoWayList.s: TwoWayList.cc.s

.PHONY : TwoWayList.s

# target to generate assembly for a file
TwoWayList.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/TwoWayList.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gTests.dir/build.make CMakeFiles/gTests.dir/TwoWayList.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.out.dir/build.make CMakeFiles/test.out.dir/TwoWayList.cc.s
.PHONY : TwoWayList.cc.s

gTests.o: gTests.cc.o

.PHONY : gTests.o

# target to build an object file
gTests.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gTests.dir/build.make CMakeFiles/gTests.dir/gTests.cc.o
.PHONY : gTests.cc.o

gTests.i: gTests.cc.i

.PHONY : gTests.i

# target to preprocess a source file
gTests.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gTests.dir/build.make CMakeFiles/gTests.dir/gTests.cc.i
.PHONY : gTests.cc.i

gTests.s: gTests.cc.s

.PHONY : gTests.s

# target to generate assembly for a file
gTests.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gTests.dir/build.make CMakeFiles/gTests.dir/gTests.cc.s
.PHONY : gTests.cc.s

lex.yy.o: lex.yy.c.o

.PHONY : lex.yy.o

# target to build an object file
lex.yy.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/lex.yy.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gTests.dir/build.make CMakeFiles/gTests.dir/lex.yy.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.out.dir/build.make CMakeFiles/test.out.dir/lex.yy.c.o
.PHONY : lex.yy.c.o

lex.yy.i: lex.yy.c.i

.PHONY : lex.yy.i

# target to preprocess a source file
lex.yy.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/lex.yy.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gTests.dir/build.make CMakeFiles/gTests.dir/lex.yy.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.out.dir/build.make CMakeFiles/test.out.dir/lex.yy.c.i
.PHONY : lex.yy.c.i

lex.yy.s: lex.yy.c.s

.PHONY : lex.yy.s

# target to generate assembly for a file
lex.yy.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/lex.yy.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gTests.dir/build.make CMakeFiles/gTests.dir/lex.yy.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.out.dir/build.make CMakeFiles/test.out.dir/lex.yy.c.s
.PHONY : lex.yy.c.s

main.o: main.cc.o

.PHONY : main.o

# target to build an object file
main.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cc.o
.PHONY : main.cc.o

main.i: main.cc.i

.PHONY : main.i

# target to preprocess a source file
main.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cc.i
.PHONY : main.cc.i

main.s: main.cc.s

.PHONY : main.s

# target to generate assembly for a file
main.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cc.s
.PHONY : main.cc.s

parser.o: parser.cc.o

.PHONY : parser.o

# target to build an object file
parser.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/parser.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gTests.dir/build.make CMakeFiles/gTests.dir/parser.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.out.dir/build.make CMakeFiles/test.out.dir/parser.cc.o
.PHONY : parser.cc.o

parser.i: parser.cc.i

.PHONY : parser.i

# target to preprocess a source file
parser.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/parser.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gTests.dir/build.make CMakeFiles/gTests.dir/parser.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.out.dir/build.make CMakeFiles/test.out.dir/parser.cc.i
.PHONY : parser.cc.i

parser.s: parser.cc.s

.PHONY : parser.s

# target to generate assembly for a file
parser.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/parser.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gTests.dir/build.make CMakeFiles/gTests.dir/parser.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.out.dir/build.make CMakeFiles/test.out.dir/parser.cc.s
.PHONY : parser.cc.s

test.o: test.cc.o

.PHONY : test.o

# target to build an object file
test.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.out.dir/build.make CMakeFiles/test.out.dir/test.cc.o
.PHONY : test.cc.o

test.i: test.cc.i

.PHONY : test.i

# target to preprocess a source file
test.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.out.dir/build.make CMakeFiles/test.out.dir/test.cc.i
.PHONY : test.cc.i

test.s: test.cc.s

.PHONY : test.s

# target to generate assembly for a file
test.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.out.dir/build.make CMakeFiles/test.out.dir/test.cc.s
.PHONY : test.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... gTests"
	@echo "... gtest"
	@echo "... gtest_main"
	@echo "... main"
	@echo "... test.out"
	@echo "... BigQ.o"
	@echo "... BigQ.i"
	@echo "... BigQ.s"
	@echo "... Comparison.o"
	@echo "... Comparison.i"
	@echo "... Comparison.s"
	@echo "... ComparisonEngine.o"
	@echo "... ComparisonEngine.i"
	@echo "... ComparisonEngine.s"
	@echo "... DBFile.o"
	@echo "... DBFile.i"
	@echo "... DBFile.s"
	@echo "... File.o"
	@echo "... File.i"
	@echo "... File.s"
	@echo "... Heap.o"
	@echo "... Heap.i"
	@echo "... Heap.s"
	@echo "... Pipe.o"
	@echo "... Pipe.i"
	@echo "... Pipe.s"
	@echo "... Record.o"
	@echo "... Record.i"
	@echo "... Record.s"
	@echo "... Schema.o"
	@echo "... Schema.i"
	@echo "... Schema.s"
	@echo "... TwoWayList.o"
	@echo "... TwoWayList.i"
	@echo "... TwoWayList.s"
	@echo "... gTests.o"
	@echo "... gTests.i"
	@echo "... gTests.s"
	@echo "... lex.yy.o"
	@echo "... lex.yy.i"
	@echo "... lex.yy.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... parser.o"
	@echo "... parser.i"
	@echo "... parser.s"
	@echo "... test.o"
	@echo "... test.i"
	@echo "... test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

